### ISSUE TITLE
Need utility for date based exclusion of stations

### ISSUE THREAD

**Issue by ccrook** [linz/linz-bernese52-util#3]
Daily processing scripts use IGS stations, but do not take account of the fact that they may be invalidated for some ITRF after deformation events.  Ideally we need a way of automatically removing these stations from the daily processing after such events, but based on a manual configuration.

The configuration could go in the datapool.  Maybe 

$D/itrf_exceptions/*datum*-exceptions.cfg

For affected stations this would contain a line something like

BADD 2020-06-01 -

ie code start-date end-date, where start-date and end-date can be -.   (Does this need to support more than one start and end date for using a station in a datum?)

Possibly could work by removing the RAW files after they have been collected, possibly this could be incorporated into GETDATA as an extra parameter to  prevent downloading into Bernese in the first place (which might be easier and more efficient).  Or is there a better way to manipulate bernese configurations to apply this?

**Comment by davecollett** [comment]
Just jumping in because I'm still subscribed to updates.. Not sure how we're generating our STA files, but isn't this the point of the "Handling of station problems" section in the STA file? so you can give a station and time duration for it to ignore the data?

I guess that section could be populated from the datum-exceptions.cfg file if that's easier.

**Comment by dnhansen50** [comment]
I had totally forgot about that as an option @davecollett ! I will invesigate. :)

**Comment by ccrook** [comment]
That sounds like the "better way" I was trying to think of!

**Comment by davecollett** [comment]
Ah, phew, wasn't sure if I was mis-interpreting the requirement...

**Comment by ccrook** [comment]
No further action needed - solved by Dave's timely reminder
